import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "House creator",
  description: "Generated by HouseCPT",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className='mx-auto max-w-[1440px]'>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
